#!/usr/bin/env bash

set -e
echo "Installing MINIMAL dotfile setup."
CONFIG="install_minimal.conf.yaml"
DOTBOT_DIR="dotbot"
DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
(cd "${DOTBOT_DIR}" && git submodule update --init --recursive)
"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"

mkdir -p ~/bin
cp -r "${BASEDIR}"/bin/* ~/bin/
