alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
alias mv='mv -i'
alias rm='rm -i'
alias cp='cp -i'
alias grep='grep --color=auto'
alias h='hg'
# alias nvim='~/nvim/nvim-linux64/nvim-linux64/bin/nvim'
alias v='nvim'
alias vm='vim --clean'
alias cdot='cd ~/.dotfiles'

alias gchat='exec google-chrome --app-id=mdpkiolbdkhdjpekfbkbmhigcaggjagi'
